branches:
  only:
  - master

language: ruby

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# necessary for docker to work
sudo: required
dist: trusty

services:
- docker

before_install:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version

matrix:
  include:
  - rvm: 2.6.3
    script: rake
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='default-centos-7'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='default-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='missing-profile-no-fail-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE && exit 1 || echo "OK"
    env: SUITE=test:integration OS='missing-profile-fail-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='chef15-compatible-inspec-ubuntu-1804' CHEF_LICENSE="accept-no-persist"
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='gem-install-core-version4-centos-7'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='gem-install-core-version3-centos-7'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='gem-install-core-version4-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='gem-install-core-version3-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='gem-install-core-version2-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='inspec-attributes-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='chef-node-enabled-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='chef-node-disabled-ubuntu-1804'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='hash-centos-7'
  - rvm: 2.6.3
    script: rake $SUITE
    env: SUITE=test:integration OS='hash-ubuntu-1804'
