addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
  - master

services: docker

env:
  global:
    - CHEF_VERSION=15.8.23
    - KITCHEN_YAML=kitchen.dokken.yml
    - CHEF_LICENSE="accept-no-persist"

before_install:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- CHEF_LICENSE="accept-no-persist" sudo chef gem install webmock
- eval "$(chef shell-init bash)"
- chef --version
- kitchen list

matrix:
  include:
  # Run integration tests with test-kitchen
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='default-centos-7'
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='default-ubuntu-1804'
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='missing-profile-no-fail-ubuntu-1804'
  - rvm: 2.6.5
    script: rake $SUITE && exit 1 || echo "OK"
    env: SUITE=test:integration OS='missing-profile-fail-ubuntu-1804'

  # Next 5 suites are disabled due to an issue with the gem() inspec resource
  # see https://github.com/chef-cookbooks/audit/issues/406
  #
  # - rvm: 2.6.5
  #   script: rake $SUITE
  #   env: SUITE=test:integration OS='chef15-compatible-inspec-ubuntu-1804'
  # Next 4 suites test running inspec 3 or 4 on audit cookbook. This is only permitted on chef 14 or older.
  # - rvm: 2.6.5
  #   script: rake $SUITE
  #   env: SUITE=test:integration OS='gem-install-core-version4-centos-7' CHEF_VERSION=14
  # - rvm: 2.6.5
  #   script: rake $SUITE
  #   env: SUITE=test:integration OS='gem-install-core-version3-centos-7' CHEF_VERSION=14
  # - rvm: 2.6.5
  #   script: rake $SUITE
  #   env: SUITE=test:integration OS='gem-install-core-version4-ubuntu-1804' CHEF_VERSION=14
  # - rvm: 2.6.5
  #   script: rake $SUITE
  #   env: SUITE=test:integration OS='gem-install-core-version3-ubuntu-1804' CHEF_VERSION=14

  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='inspec-attributes-ubuntu-1804'
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='chef-node-enabled-ubuntu-1804'
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='chef-node-disabled-ubuntu-1804'
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='hash-centos-7'
  - rvm: 2.6.5
    script: rake $SUITE
    env: SUITE=test:integration OS='hash-ubuntu-1804'
